### ISSUE TITLE
Suitability for binning Eukaryotic viral sequences derived from SAGs 

### ISSUE THREAD

**Issue by felipehcoutinho** [AnantharamanLab/vRhyme#13]
Hi there! And congratulations on putting together another amazing tool!

I am writing to ask your opinion on the suitability of vRhyme for a specific dataset I've been working with: A dataset of 80 Single Amplified Genomes (SAGs) from unicellular marine eukaryotes. Each SAG was sequenced and assembled idividually, and among the scaffolds about 100 were identified as genome fragments derived from eukaryotic viruses (distantly related to NCLDV). Most of the scaffolds are small fragments (average 10 Kbp), so I was interested in using vRhyme to bin these scaffolds to improve genome recovery. My questions are:
1. The training dataset for vRhyme was made up of prokaryotic viruses, and the manuscript mentions that Rhyme performed well when binning eukaryotic viruses (Table S6). Yet it seems that this test dataset was somehwat small, as it was composded of only 4 genomes. Do you believe it is reasonable to extrapolate this performance metrics to other eukaryotic viral groups (or at least to large dsDNA genomes)?
2. Considering that the sequencing in my dataset was done from SAGs, and not metagenomes, do you believe the scaffold coverage data could reliably be used for binning through vRhyme? Right now Im inclined to belive it wouldnt, first because the MDA amplification step is expected to introduce a lot of noise in the coverage patterns. Second, because the scaffold coverage in SAGs would reflect the abundance of the viruses in each well and not in the overall community, possibly being biased by the stage/efficiency of viral replication in each specific cell. Third, the SAGs were selected to maximize phylogenetic diversity, meaning that very few SAGs belong to the same species (or even phylum for that matter). Hence the scaffold X sample coverage matrix is really sparse, each viral scaffold shows up in just a few SAGs and is absent from all the others. I think such a sparse matrix would lead to a lot of spurious coverage correlations which would make it unsitable for the ML algorithims to work with, right?
3. Which brings me to my final question: Would it be possible to performe the binning without the coverage data, relying solely on the nucleotide content metrics? If so, do you have any benchmarking data on the performance of vRhyme in those cases that you could share?

Thank you in advance!

**Comment by KrisKieft** [comment]
Hi,

These are great questions and I unfortunately am going to provide a fairly uninteresting answer. Yes, vRhyme should work find on dsDNA NCLDVs, but I don't think it's the best option for you dataset. The low coverage, use of MDA on SAGs, and high strain/species similarity are going to make the results fairly messy. I think if you do end up binning just to see the results you should be pretty skeptical and definitely consider some manual curation if possible. vRhyme and most other tools rely heavily on coverage data, so that will bias your results a lot, but sparse data can actually be a positive as long as the sparseness has a pattern between viral SAGs (coverage patterns is more important than coverage depth). It's possible that VAMB (not sure if PHAMB is necessarily that useful here) can pull these out better as it relies and pulls out genomic information differently. My overall suggestion would be to use vRhyme but know that the results will be messy and try out VAMB with the same caveats in mind. Let me know if you have any more questions on this.

Kris

**Comment by felipehcoutinho** [comment]
Thanks for the input!
